---

- block:
    - name: Create UnitPal root folder if it does not exist 
      file:
        path: "{{ unitpal_root }}"
        state: directory
        owner: unitpal
        group: unitpal
        mode: 0755
      become: yes
      
    - name: Check out UnitPal
      git: >
        dest={{ unitpal_root }}
        repo={{ unitpal_repo }}
        version={{ unitpal_version }}
        update=yes
        force=yes

      become_user: unitpal

    - name: Install npm dependencies
      command: npm run install-deps
      args: 
        chdir: "{{ unitpal_root }}"
    
    - name: Compiling client & server
      command: npm run build-all
      args: 
        chdir: "{{ unitpal_root }}"

    - name: Create revved files and replace their names
      command: npm run rev-replace
      args: 
        chdir: "{{ unitpal_root }}"
      become_user: unitpal

    - name: Get revved css file names
      command: "find {{ unitpal_root }}/assets/revved-css-files/ -type f"
      register: css_files_to_copy

    - name: Copy revved css files
      copy:
        src: "{{ item }}"
        dest: "{{ unitpal_root }}/assets/dist/client/static-assets/css/"
        remote_src: true
      with_items: "{{css_files_to_copy.stdout_lines }}"
      become: yes

    - name: Get revved js file names
      command: "find {{ unitpal_root }}/assets/revved-js-files/ -type f"
      register: js_files_to_copy

    - name: Copy revved js files
      copy:
        src: "{{ item }}"
        dest: "{{ unitpal_root }}/assets/dist/client/build/"
        remote_src: true
      with_items: "{{js_files_to_copy.stdout_lines }}"
      become: yes

    - name: Delete original views
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ unitpal_root }}/views/internal.ejs"
        - "{{ unitpal_root }}/views/external.ejs"

    - name: Replace modified views
      copy:
        src: "{{ item }}"
        dest: "{{ unitpal_root }}/views/"
        remote_src: true
      with_items:
        - "{{ unitpal_root }}/assets/rev-replace-output/internal.ejs"
        - "{{ unitpal_root }}/assets/rev-replace-output/external.ejs"
      become_user: unitpal

    - name: Clean rev-replace process
      command: npm run clean-rev-replace
      args: 
        chdir: "{{ unitpal_root }}"

    - name: Create UnitPal environment files
      template: src={{ item }}
                dest={{ unitpal_root }}/config/env/{{ item | regex_replace('\.j2$', '') }}
                backup=yes
                owner=unitpal group=unitpal mode=0664
      with_items:
        - azure.js.j2

  become: yes
