before_script:
 - npm run forever-stop
 - npm run install-deps
rspec:
  script:
   - npm run build-all
   - npm run server-tests
   - npm run forever-start
   - ./test_BREAK.sh
   - echo "Finished the build for the Development Branch"