stages:
  - test
  - deploy

test on demo3AT:
  stage: test
  script:
    - npm run forever-stop
    - npm run install-deps
    - npm run build-all
    - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run server-tests
    - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run forever-start
    - echo "Finished the build for the Production Branch"
  environment:
    name: demo

deploy on staging:
  stage: deploy
  script:
    - echo "This should be replaced with deployment script"
  environment:
    name: staging
  only:
    - development

deploy on production:
  stage: deploy
  script:
    - ./ansible/azure_install.sh
  environment:
    name: production
  when: manual
  only:
    - master
