stages:
  - test
  - deploy
  - run

test on demo3AT:
  stage: test
  script:
    - npm run forever-stop
    - npm run install-deps
    - npm run build-all
    - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run server-tests
  environment:
    name: demo

deploy on staging:
  stage: deploy
  script:
    - ./ansible/deploy.sh staging
  environment:
    name: staging
  only:
    - development

deploy on production:
  stage: deploy
  script:
    - ./ansible/deploy.sh production
  environment:
    name: production
  when: manual
  only:
    - master

run on demo3AT:
  stage: run
  script:
    - npm run install-deps
    - npm run build-all
    - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run forever-start
  environment:
    name: demo