before_script:
 - npm run forever-stop
 - npm run install-deps

build_test_run:
  script:
   - npm run build-all
   - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run server-tests
   - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run forever-start
   - echo "Finished the build for the Production Branch"
  
deploy:
  script:
   - ./ansible/azure_install.sh
  only:
   - master