stages:
  - build
  - test
  - deploy
  - run

build on demo3AT:
  stage: build
  script:
    - npm run forever-stop
    - npm run install-deps
    - npm run build-all
  cache:
    key: ${CI_BUILD_REF_NAME}
    cache:
      untracked: true
  allow_failure: false
  environment:
    name: demo

test on demo3AT:
  stage: test
  script:
    - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run server-tests
  allow_failure: false
  environment:
    name: demo

deploy on staging:
  stage: deploy
  script:
    - echo "This should be replaced with deployment script"
  environment:
    name: staging
  only:
    - development

deploy on production:
  stage: deploy
  script:
    - ./ansible/azure_install.sh
  environment:
    name: production
  allow_failure: false
  when: manual
  only:
    - master

run on demo3AT:
  stage: run
  script:
    - npm run install-deps
    - npm run build-all
    - MONGO_USER=demothangle MONGO_PASSWD=Anisdy\$57m! npm run forever-start
  environment:
    name: demo
