import {ABaseSetting} from './ABaseSetting';
import {SettingMetadataDO, SettingType} from '../../../../../../../data-layer/settings/data-objects/common/SettingMetadataDO';
import {CountryDO} from '../../../../../../../data-layer/common/data-objects/country/CountryDO';
import {CountrySettingDO} from '../../../../../../../data-layer/settings/data-objects/country/CountrySettingDO';

export class Countries extends ABaseSetting {
    constructor() {
        super(SettingType.Countries, "Countries");
    }

    public getCountrySettingDO(): CountrySettingDO {
        var readCountries = this.dataSet;
        var toAddCountries: CountryDO[] = [];
        readCountries.forEach((readCountry: { name: string, code: string, inEU: boolean }) => {
            var countryDO = new CountryDO();
            countryDO.code = readCountry.code;
            countryDO.name = readCountry.name;
            countryDO.inEU = readCountry.inEU;
            toAddCountries.push(countryDO);
        });
        var countrySettingDO = new CountrySettingDO();
        countrySettingDO.metadata = this.getSettingMetadata();
        countrySettingDO.value = toAddCountries;
        return countrySettingDO;
    }

    private dataSet: { name: string, code: string, inEU: boolean }[] = [
        { name: 'Afghanistan', code: 'AF', inEU: false },
        { name: 'Åland Islands', code: 'AX', inEU: false },
        { name: 'Albania', code: 'AL', inEU: false },
        { name: 'Algeria', code: 'DZ', inEU: false }, ,
        { name: 'American Samoa', code: 'AS', inEU: false },
        { name: 'Andorra', code: 'AD', inEU: false },
        { name: 'Angola', code: 'AO', inEU: false },
        { name: 'Anguilla', code: 'AI', inEU: false },
        { name: 'Antarctica', code: 'AQ', inEU: false },
        { name: 'Antigua and Barbuda', code: 'AG', inEU: false },
        { name: 'Argentina', code: 'AR', inEU: false },
        { name: 'Armenia', code: 'AM', inEU: false },
        { name: 'Aruba', code: 'AW', inEU: false },
        { name: 'Australia', code: 'AU', inEU: false },
        { name: 'Austria', code: 'AT', inEU: true },
        { name: 'Azerbaijan', code: 'AZ', inEU: false },
        { name: 'Bahamas', code: 'BS', inEU: false },
        { name: 'Bahrain', code: 'BH', inEU: false },
        { name: 'Bangladesh', code: 'BD', inEU: false },
        { name: 'Barbados', code: 'BB', inEU: false },
        { name: 'Belarus', code: 'BY', inEU: false },
        { name: 'Belgium', code: 'BE', inEU: true },
        { name: 'Belize', code: 'BZ', inEU: false },
        { name: 'Benin', code: 'BJ', inEU: false },
        { name: 'Bermuda', code: 'BM', inEU: false },
        { name: 'Bhutan', code: 'BT', inEU: false },
        { name: 'Bolivia', code: 'BO', inEU: false },
        { name: 'Bosnia and Herzegovina', code: 'BA', inEU: false },
        { name: 'Botswana', code: 'BW', inEU: false },
        { name: 'Bouvet Island', code: 'BV', inEU: false },
        { name: 'Brazil', code: 'BR', inEU: false },
        { name: 'British Indian Ocean Territory', code: 'IO', inEU: false },
        { name: 'Brunei Darussalam', code: 'BN', inEU: false },
        { name: 'Bulgaria', code: 'BG', inEU: true },
        { name: 'Burkina Faso', code: 'BF', inEU: false },
        { name: 'Burundi', code: 'BI', inEU: false },
        { name: 'Cambodia', code: 'KH', inEU: false },
        { name: 'Cameroon', code: 'CM', inEU: false },
        { name: 'Canada', code: 'CA', inEU: false },
        { name: 'Cape Verde', code: 'CV', inEU: false },
        { name: 'Cayman Islands', code: 'KY', inEU: false },
        { name: 'Central African Republic', code: 'CF', inEU: false },
        { name: 'Chad', code: 'TD', inEU: false },
        { name: 'Chile', code: 'CL', inEU: false },
        { name: 'China', code: 'CN', inEU: false },
        { name: 'Christmas Island', code: 'CX', inEU: false },
        { name: 'Cocos (Keeling) Islands', code: 'CC', inEU: false },
        { name: 'Colombia', code: 'CO', inEU: false },
        { name: 'Comoros', code: 'KM', inEU: false },
        { name: 'Congo', code: 'CG', inEU: false },
        { name: 'Congo, The Democratic Republic of the', code: 'CD', inEU: false },
        { name: 'Cook Islands', code: 'CK', inEU: false },
        { name: 'Costa Rica', code: 'CR', inEU: false },
        { name: 'Cote D\'Ivoire', code: 'CI', inEU: false },
        { name: 'Croatia', code: 'HR', inEU: true },
        { name: 'Cuba', code: 'CU', inEU: false },
        { name: 'Cyprus', code: 'CY', inEU: true },
        { name: 'Czech Republic', code: 'CZ', inEU: true },
        { name: 'Denmark', code: 'DK', inEU: true },
        { name: 'Djibouti', code: 'DJ', inEU: false },
        { name: 'Dominica', code: 'DM', inEU: false },
        { name: 'Dominican Republic', code: 'DO', inEU: false },
        { name: 'Ecuador', code: 'EC', inEU: false },
        { name: 'Egypt', code: 'EG', inEU: false },
        { name: 'El Salvador', code: 'SV', inEU: false },
        { name: 'Equatorial Guinea', code: 'GQ', inEU: false },
        { name: 'Eritrea', code: 'ER', inEU: false },
        { name: 'Estonia', code: 'EE', inEU: true },
        { name: 'Ethiopia', code: 'ET', inEU: false },
        { name: 'Falkland Islands (Malvinas)', code: 'FK', inEU: false },
        { name: 'Faroe Islands', code: 'FO', inEU: false },
        { name: 'Fiji', code: 'FJ', inEU: false },
        { name: 'Finland', code: 'FI', inEU: true },
        { name: 'France', code: 'FR', inEU: true },
        { name: 'French Guiana', code: 'GF', inEU: false },
        { name: 'French Polynesia', code: 'PF', inEU: false },
        { name: 'French Southern Territories', code: 'TF', inEU: false },
        { name: 'Gabon', code: 'GA', inEU: false },
        { name: 'Gambia', code: 'GM', inEU: false },
        { name: 'Georgia', code: 'GE', inEU: false },
        { name: 'Germany', code: 'DE', inEU: true },
        { name: 'Ghana', code: 'GH', inEU: false },
        { name: 'Gibraltar', code: 'GI', inEU: false },
        { name: 'Greece', code: 'GR', inEU: true },
        { name: 'Greenland', code: 'GL', inEU: false },
        { name: 'Grenada', code: 'GD', inEU: false },
        { name: 'Guadeloupe', code: 'GP', inEU: false },
        { name: 'Guam', code: 'GU', inEU: false },
        { name: 'Guatemala', code: 'GT', inEU: false },
        { name: 'Guernsey', code: 'GG', inEU: false },
        { name: 'Guinea', code: 'GN', inEU: false },
        { name: 'Guinea-Bissau', code: 'GW', inEU: false },
        { name: 'Guyana', code: 'GY', inEU: false },
        { name: 'Haiti', code: 'HT', inEU: false },
        { name: 'Heard Island and Mcdonald Islands', code: 'HM', inEU: false },
        { name: 'Holy See (Vatican City State)', code: 'VA', inEU: false },
        { name: 'Honduras', code: 'HN', inEU: false },
        { name: 'Hong Kong', code: 'HK', inEU: false },
        { name: 'Hungary', code: 'HU', inEU: true },
        { name: 'Iceland', code: 'IS', inEU: false },
        { name: 'India', code: 'IN', inEU: false },
        { name: 'Indonesia', code: 'ID', inEU: false },
        { name: 'Iran, Islamic Republic Of', code: 'IR', inEU: false },
        { name: 'Iraq', code: 'IQ', inEU: false },
        { name: 'Ireland', code: 'IE', inEU: true },
        { name: 'Isle of Man', code: 'IM', inEU: false },
        { name: 'Israel', code: 'IL', inEU: false },
        { name: 'Italy', code: 'IT', inEU: true },
        { name: 'Jamaica', code: 'JM', inEU: false },
        { name: 'Japan', code: 'JP', inEU: false },
        { name: 'Jersey', code: 'JE', inEU: false },
        { name: 'Jordan', code: 'JO', inEU: false },
        { name: 'Kazakhstan', code: 'KZ', inEU: false },
        { name: 'Kenya', code: 'KE', inEU: false },
        { name: 'Kiribati', code: 'KI', inEU: false },
        { name: 'Korea, Democratic People\'S Republic of', code: 'KP', inEU: false },
        { name: 'Korea, Republic of', code: 'KR', inEU: false },
        { name: 'Kuwait', code: 'KW', inEU: false },
        { name: 'Kyrgyzstan', code: 'KG', inEU: false },
        { name: 'Lao People\'S Democratic Republic', code: 'LA', inEU: false },
        { name: 'Latvia', code: 'LV', inEU: true },
        { name: 'Lebanon', code: 'LB', inEU: false },
        { name: 'Lesotho', code: 'LS', inEU: false },
        { name: 'Liberia', code: 'LR', inEU: false },
        { name: 'Libyan Arab Jamahiriya', code: 'LY', inEU: false },
        { name: 'Liechtenstein', code: 'LI', inEU: false },
        { name: 'Lithuania', code: 'LT', inEU: true },
        { name: 'Luxembourg', code: 'LU', inEU: true },
        { name: 'Macao', code: 'MO', inEU: false },
        { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', inEU: false },
        { name: 'Madagascar', code: 'MG', inEU: false },
        { name: 'Malawi', code: 'MW', inEU: false },
        { name: 'Malaysia', code: 'MY', inEU: false },
        { name: 'Maldives', code: 'MV', inEU: false },
        { name: 'Mali', code: 'ML', inEU: false },
        { name: 'Malta', code: 'MT', inEU: true },
        { name: 'Marshall Islands', code: 'MH', inEU: false },
        { name: 'Martinique', code: 'MQ', inEU: false },
        { name: 'Mauritania', code: 'MR', inEU: false },
        { name: 'Mauritius', code: 'MU', inEU: false },
        { name: 'Mayotte', code: 'YT', inEU: false },
        { name: 'Mexico', code: 'MX', inEU: false },
        { name: 'Micronesia, Federated States of', code: 'FM', inEU: false },
        { name: 'Moldova, Republic of', code: 'MD', inEU: false },
        { name: 'Monaco', code: 'MC', inEU: false },
        { name: 'Mongolia', code: 'MN', inEU: false },
        { name: 'Montserrat', code: 'MS', inEU: false },
        { name: 'Morocco', code: 'MA', inEU: false },
        { name: 'Mozambique', code: 'MZ', inEU: false },
        { name: 'Myanmar', code: 'MM', inEU: false },
        { name: 'Namibia', code: 'NA', inEU: false },
        { name: 'Nauru', code: 'NR', inEU: false },
        { name: 'Nepal', code: 'NP', inEU: false },
        { name: 'Netherlands', code: 'NL', inEU: true },
        { name: 'Netherlands Antilles', code: 'AN', inEU: false },
        { name: 'New Caledonia', code: 'NC', inEU: false },
        { name: 'New Zealand', code: 'NZ', inEU: false },
        { name: 'Nicaragua', code: 'NI', inEU: false },
        { name: 'Niger', code: 'NE', inEU: false },
        { name: 'Nigeria', code: 'NG', inEU: false },
        { name: 'Niue', code: 'NU', inEU: false },
        { name: 'Norfolk Island', code: 'NF', inEU: false },
        { name: 'Northern Mariana Islands', code: 'MP', inEU: false },
        { name: 'Norway', code: 'NO', inEU: false },
        { name: 'Oman', code: 'OM', inEU: false },
        { name: 'Pakistan', code: 'PK', inEU: false },
        { name: 'Palau', code: 'PW', inEU: false },
        { name: 'Palestinian Territory, Occupied', code: 'PS', inEU: false },
        { name: 'Panama', code: 'PA', inEU: false },
        { name: 'Papua New Guinea', code: 'PG', inEU: false },
        { name: 'Paraguay', code: 'PY', inEU: false },
        { name: 'Peru', code: 'PE', inEU: false },
        { name: 'Philippines', code: 'PH', inEU: false },
        { name: 'Pitcairn', code: 'PN', inEU: false },
        { name: 'Poland', code: 'PL', inEU: true },
        { name: 'Portugal', code: 'PT', inEU: true },
        { name: 'Puerto Rico', code: 'PR', inEU: false },
        { name: 'Qatar', code: 'QA', inEU: false },
        { name: 'Reunion', code: 'RE', inEU: false },
        { name: 'Romania', code: 'RO', inEU: true },
        { name: 'Russian Federation', code: 'RU', inEU: false },
        { name: 'RWANDA', code: 'RW', inEU: false },
        { name: 'Saint Helena', code: 'SH', inEU: false },
        { name: 'Saint Kitts and Nevis', code: 'KN', inEU: false },
        { name: 'Saint Lucia', code: 'LC', inEU: false },
        { name: 'Saint Pierre and Miquelon', code: 'PM', inEU: false },
        { name: 'Saint Vincent and the Grenadines', code: 'VC', inEU: false },
        { name: 'Samoa', code: 'WS', inEU: false },
        { name: 'San Marino', code: 'SM', inEU: false },
        { name: 'Sao Tome and Principe', code: 'ST', inEU: false },
        { name: 'Saudi Arabia', code: 'SA', inEU: false },
        { name: 'Senegal', code: 'SN', inEU: false },
        { name: 'Serbia and Montenegro', code: 'CS', inEU: false },
        { name: 'Seychelles', code: 'SC', inEU: false },
        { name: 'Sierra Leone', code: 'SL', inEU: false },
        { name: 'Singapore', code: 'SG', inEU: false },
        { name: 'Slovakia', code: 'SK', inEU: true },
        { name: 'Slovenia', code: 'SI', inEU: true },
        { name: 'Solomon Islands', code: 'SB', inEU: false },
        { name: 'Somalia', code: 'SO', inEU: false },
        { name: 'South Africa', code: 'ZA', inEU: false },
        { name: 'South Georgia and the South Sandwich Islands', code: 'GS', inEU: false },
        { name: 'Spain', code: 'ES', inEU: true },
        { name: 'Sri Lanka', code: 'LK', inEU: false },
        { name: 'Sudan', code: 'SD', inEU: false },
        { name: 'Suriname', code: 'SR', inEU: false },
        { name: 'Svalbard and Jan Mayen', code: 'SJ', inEU: false },
        { name: 'Swaziland', code: 'SZ', inEU: false },
        { name: 'Sweden', code: 'SE', inEU: true },
        { name: 'Switzerland', code: 'CH', inEU: false },
        { name: 'Syrian Arab Republic', code: 'SY', inEU: false },
        { name: 'Taiwan, Province of China', code: 'TW', inEU: false },
        { name: 'Tajikistan', code: 'TJ', inEU: false },
        { name: 'Tanzania, United Republic of', code: 'TZ', inEU: false },
        { name: 'Thailand', code: 'TH', inEU: false },
        { name: 'Timor-Leste', code: 'TL', inEU: false },
        { name: 'Togo', code: 'TG', inEU: false },
        { name: 'Tokelau', code: 'TK', inEU: false },
        { name: 'Tonga', code: 'TO', inEU: false },
        { name: 'Trinidad and Tobago', code: 'TT', inEU: false },
        { name: 'Tunisia', code: 'TN', inEU: false },
        { name: 'Turkey', code: 'TR', inEU: false },
        { name: 'Turkmenistan', code: 'TM', inEU: false },
        { name: 'Turks and Caicos Islands', code: 'TC', inEU: false },
        { name: 'Tuvalu', code: 'TV', inEU: false },
        { name: 'Uganda', code: 'UG', inEU: false },
        { name: 'Ukraine', code: 'UA', inEU: false },
        { name: 'United Arab Emirates', code: 'AE', inEU: false },
        { name: 'United Kingdom', code: 'GB', inEU: true },
        { name: 'United States', code: 'US', inEU: false },
        { name: 'United States Minor Outlying Islands', code: 'UM', inEU: false },
        { name: 'Uruguay', code: 'UY', inEU: false },
        { name: 'Uzbekistan', code: 'UZ', inEU: false },
        { name: 'Vanuatu', code: 'VU', inEU: false },
        { name: 'Venezuela', code: 'VE', inEU: false },
        { name: 'Viet Nam', code: 'VN', inEU: false },
        { name: 'Virgin Islands, British', code: 'VG', inEU: false },
        { name: 'Virgin Islands, U.S.', code: 'VI', inEU: false },
        { name: 'Wallis and Futuna', code: 'WF', inEU: false },
        { name: 'Western Sahara', code: 'EH', inEU: false },
        { name: 'Yemen', code: 'YE', inEU: false },
        { name: 'Zambia', code: 'ZM', inEU: false },
        { name: 'Zimbabwe', code: 'ZW', inEU: false }
    ];
}