---
- name: Install UnitPal
  hosts: appservers

  roles:
    - git
    - node
    - unitpal
    - pm2
    - nginx
    - { role: librato.librato, librato_email: {{ librato_email }}, librato_token: {{ librato_api_token }} }